### ISSUE TITLE
Symbol auto-completion

### ISSUE THREAD

**Issue by PooriaT** [PooriaT/StockUP#48]
### Summary
While typing suggesting symbols to the user

### Steps to Reproduce
1. Step one
2. Step two
3. Step three

### What is Expected
Describe what you expected to happen.

### What Actually Happens
Describe what actually happens.

### Additional Information
Any other relevant information (e.g., logs, screenshots).

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented an autocomplete feature for stock symbols in the stock_info_page() function. This allows users to see suggestions while typing, improving the user experience and reducing errors.

You can review changes in this commit: https://github.com/lattaai13/PooriaT-StockUP-48/commit/a2a659001958d2e82f8f919cb3c67d7569a8176a.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
